dist: trusty
sudo: false

addons:
  sonarcloud:
    organization: "theodor-lindberg"
    token:
      secure: "YJPO9SJ3Q/4cEKvTO7087gSd7exGeB0ga6jFhdkniNzGnoGbc3bnDpk8AdnWj4xXfGSEO519KfJ8SQVBH/aruxnW+wIKNbT+ucoEpk+vhRlnddldkEq6Erbt2gTcj3wUsdYnDWJ8++Bc8Hl0AVB36Wjr0rr4rBjpiiVyJrX8IFwbEbaH9zB/PB7N6ik74r+7CE9y7M69VY+CKz4meZ4Wu8IVH3DgxSy1dh7cG19b0BXNegemJpEwjMtrNs7zALKm8+oP4K2d1sAI9do1i8GXT0XzqbKdEyGeIqeA+7oJUe0K3TfWGPQY0DIw2F4IptLKiq89Xes10UVpKlKkKGyCjbUF5kG2oUPwMT1wGokyOApJcvIVTxP1VhdbPMEkxriIcdbD+slTwkE7yc8GgRlyE/ixgir2ydKHufLTRmLnX7dn+mL/N9aBEQ8TY3ONpDO66YNwYCFjl9pK1Y721aOMu1vDNgGOyZKrVvn3kXLCSN1FbxBFdhpjO2TMQYmQ9YYtKnHKYA/Ah2D7n8aBZyAPrslZ3VqdarBAnVqejCHM7VvXbbJsBInLLF9/0ZowUOvJgwWaZiPQf6u7XM37mxux6RZncs8bCFZ47npHcna5LqblY+nbIghhDvMN6rQPHnpaFnPlGaJIOZNJy+3lPZt4qcUZybh19eGESFzxYxcwukY="

script:
  - make clean
  # Wraps the compilation with the Build Wrapper to generate configuration (used
  # later by the SonarQube Scanner) into the "bw-output" folder
  - build-wrapper-linux-x86-64 --out-dir bw-output make all
  # Execute some tests
  - make test
  # And finally run the SonarQube analysis - read the "sonar-project.properties"
  # file to see the specific configuration
  - sonar-scanner

cache:
  directories:
    - '$HOME/.sonar/cache'

# Don't copy the following part if your usnig this project as a starting point of yours
#notifications:
#  email: false
#  webhooks:
#    - secure: "ouG1h56cuJejRCsCHZOc4X0lDrpZyaiXOmzYMX0qnKXsjx17ZRMdkunA11pzrABAzO2l4rq5aMMNLs2Obwp/jiuV11SeyucgGzgqwdUQivR9noqpI9yq9VeaRBuK8dHMG0RtRVH0HAdv53VaPBYExj860FdBOUMzgvxE1v7EPIqpfbC9XcIPkZoIkMCP0E8nBE5R3is1ZY49fgFi3+UpQP5EjfeX2E8n0tHzs6uwO7QcnB0GNfUcjKGShjxecPEB77oIv8kcaIEqUBdRsuwwIfidtOsgggGpchaeJ1kEVTESLDz7QPf73ng4j9LP7whb0rtVZYpUr+TI0MoLZu5/WptErelei1eBniHR8CbSbhi6FQ07Pyx7DAc9xmBjgBVbLY/RROGfguAPd+AWn/E6WthN31q6/EpeX7wOkNDjOk6CUPqGgHpQ4BJDy82uV8N3H/uMaonwCeyxKhWxlOWGWBEUwN3rXRt63wMNYABemBiXdjlVxnh1949Drhd+LBS1ebeikq5SmOrZCA2IrHPcTEAtU7bCaCoe5vOm9XYQmxfrNg88aiQR26SjVK2A55x2t8DXqkjS8/7Q9k7gg5CBG5iEOdrSPw8UKTuy2t8SaUlaidyZTdbUT5L3v/UKgucex+hRN8AzWDJ6u9Hl2qdaxZKOSJjo+NV7ZsLxrVvafrg="
#  on_start: always
